parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: hispanos_vic
    database_user: hispanos_vic
    database_password: 18693713
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 95d0639e3b647d86848a647edbe93795d9dce409
    database_path: null