parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: lavictoria2
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: es
    secret: 95d0639e3b647d86848a647edbe93795d9dce409
    database_path: null
