jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Proyecto\PrincipalBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: ProyectoPrincipalBundle:Usuario, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /admin/acceso
                check_path:  /admin/login_check
                default_target_path: /admin/es
            logout:
              path: /logout
              target: /admin/es
    access_control:
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/acceso, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/cuenta/guardar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
