proyecto_front_homepage:
    pattern:  /
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }
proyecto_front_organizacion:
    pattern:  /organizacion
    defaults: { _controller: ProyectoFrontBundle:Default:organizacion }
proyecto_front_organizacion_articulo:
    pattern:  /organizacion/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:articulo,id: '1' }
proyecto_front_informacion:
    pattern:  /informacion
    defaults: { _controller: ProyectoFrontBundle:Default:informacion }
proyecto_front_informacion_articulo:
    pattern:  /informacion/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:articulo,id: '1' }
proyecto_front_descargas:
    pattern:  /descargas
    defaults: { _controller: ProyectoFrontBundle:Default:descargas }
proyecto_front_contacto:
    pattern:  /contacto
    defaults: { _controller: ProyectoFrontBundle:Default:contacto }
proyecto_front_registro:
    pattern:  /registro
    defaults: { _controller: ProyectoFrontBundle:Users:registro }
proyecto_front_perfil:
    pattern:  /perfil
    defaults: { _controller: ProyectoFrontBundle:Users:perfil }
proyecto_front_entrada:
    pattern:  /entrada
    defaults: { _controller: ProyectoFrontBundle:Users:entrada }
proyecto_front_validacion:
    pattern:  /validacion
    defaults: { _controller: ProyectoFrontBundle:Users:validacion }
proyecto_front_cerrarsesion:
    pattern:  /logout
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }