proyecto_front_homepage:
    pattern:  /
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }
proyecto_front_biografia:
    pattern:  /biografia
    defaults: { _controller: ProyectoFrontBundle:Default:biografia }
proyecto_front_noticias:
    pattern:  /noticias
    defaults: { _controller: ProyectoFrontBundle:Default:noticias }
proyecto_front_programacion:
    pattern:  /programacion
    defaults: { _controller: ProyectoFrontBundle:Default:programacion }
proyecto_front_talleres:
    pattern:  /talleres
    defaults: { _controller: ProyectoFrontBundle:Default:talleres }
proyecto_front_article:
    pattern:  /article/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:article }
proyecto_front_gastrobar:
    pattern:  /gastrobar
    defaults: { _controller: ProyectoFrontBundle:Default:gastrobar }
proyecto_front_contacto:
    pattern:  /contacto
    defaults: { _controller: ProyectoFrontBundle:Default:contacto }
proyecto_front_validacion:
    pattern:  /validacion
    defaults: { _controller: ProyectoFrontBundle:Users:validacion }
proyecto_front_cerrarsesion:
    pattern:  /logout
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }
proyecto_front_reservation:
    pattern:  /reservation/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:reservation }
